---
on:
  workflow_run:
    workflows: [".NET Build and Test"]
    types: [completed]
    branches: [main]
name: Push to Live
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: live
    permissions:
      packages: read
    steps:
        # checkout the repo
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      - name: Login via Azure CLI
        uses: azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lowercase image name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}live${{ github.run_number }}
          image: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          registry-login-server: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: bottomly-live
          location: uk south
          environment-variables: bottomly_giphy_api_key=${{ secrets.GIPHY_API_KEY }}
            bottomly_google_api_key=${{ secrets.GOOGLE_API_KEY }}
            bottomly_google_cse_id=${{ secrets.GOOGLE_CSE_ID }}
            bottomly_slack_bot_token=${{ secrets.SLACK_TOKEN }}
            bottomly_slack_app_token=${{ secrets.SLACK_APP_TOKEN }}
            bottomly_prefix=${{ secrets.PREFIX }}
            bottomly_env=${{ secrets.ENV }}
            ConnectionStrings__mongodb=${{ secrets.MONGO_CONN_STR }}
            bottomly_github_token=${{ secrets.RELEASE_HISTORY_TOKEN }}
